<nav class="navbar customNavbar" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Brand name</a>
        </div>
        <?php
       $elements = new Elements();
        $elements->getMenu();
        ?>
    </div>
</nav>
<div class="mainWrapper">
    <div class="innerWrapper">
<div class="container">
	<?php
	echo $this->flashSession->output();
	echo $this->getContent();
	?>

    <footer>

    </footer>
</div>
</div>
</div>