<div class="login-screen"></div>
<div class="login-center">
    <div id="size_25"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-8">
                <div class="login" id="card">
                    <div class="front signin_form">
                        <p>Авторизуйтесь</p>
                        <?php
                            $this->view->partial('partial/login_form');
                        ?>
                    </div>
                    <div class="back signup_form" style="opacity: 0;">
                        <p>Создание нового акаунта</p>
	                    <?php
	                        $this->view->partial('partial/register_form');
	                    ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
