<?php
echo $this->getContent();
?>

<div class="page-header">
    <h2>Contact Us</h2>
</div>

<p>Send us a message and let us know how we can help. Please be as descriptive as possible as it will help us serve you
    better.</p>

<?= $this->tag->form(["contact/send", 'class' => 'login-form', 'role' => 'form']) ?>
<fieldset>
    <div class="form-group">
        <input type="text" name="name" class="form-control">
    </div>
    <div class="form-group">
        <input type="text" name="email" class="form-control">
    </div>
    <div class="form-group">
        <input type="text" name="comments" class="form-control">
    </div>
    <div class="form-group">
		<?= $this->tag->submitButton(["Send", "class" => "btn btn-primary btn-large"]) ?>
    </div>
</fieldset>
<?= $this->tag->endForm() ?>
