<?php
echo $this->getContent();
?>

<div class="page-header">
    <h2>Contact Us</h2>
</div>

<p class="form_title">Send us a message and let us know how we can help. Please be as descriptive as possible as it will help us serve you
    better.</p>

<?= $this->tag->form(["contact/send", 'class' => 'login-form', 'role' => 'form']) ?>
<fieldset>
    <div class="form-group">
        <input type="text" name="name" class="form-control" placeholder="Enter your name">
    </div>
    <div class="form-group">
        <input type="text" name="email" class="form-control" placeholder=" Enter your email">
    </div>
    <div class="form-group">
<!--        <input type="text" name="comments" class="form-control">-->
        <textarea name="comments" id="comments"  rows="3" placeholder="Enter your message"></textarea>
    </div>
    <div class="form-group">
		<?= $this->tag->submitButton(["Send", "class" => "btn btn-primary btn_custom"]) ?>
    </div>
</fieldset>
<?= $this->tag->endForm() ?>
