<?php use Phalcon\Tag as Tag; ?>
<?= Tag::setDoctype(Tag::HTML5); ?>
<html>
<head>
    <meta charset="utf-8">
	<?= Tag::getTitle() ?>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<?= Tag::stylesheetLink('css/bootstrap.min.css') ?>
	<?= Tag::stylesheetLink('css/font-awesome.min.css') ?>
	<?= Tag::stylesheetLink('css/custom_template.css') ?>
</head>
<body>
<?= $this->getContent() ?>
<?= Tag::javascriptInclude('js/jquery.min.js') ?>
<?= Tag::javascriptInclude('js/bootstrap.js') ?>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jQuery-Flip/1.0.18/jquery.flip.js"></script>
<?= Tag::javascriptInclude('js/custom_template.js') ?>
</body>
</html>