    <div class="page-header">
        <h2>Log In</h2>
    </div>
	<?= $this->tag->form(["login", 'class' => 'login-form']) ?>
    <div class="form-group">
        <label for="email">Username/Email</label>
        <div class="controls">
            <input type="text" name="email">
        </div>
    </div>
    <div class="form-group">
        <label for="password">Password</label>
        <div class="controls">
            <input type="password" name="password">
        </div>
    </div>
    <div class="form-group sign-btn">
		<?= $this->tag->submitButton(["Вход", "class" => "btn"]) ?>
        <p>
            <br>
            <strong>Нету акаунта? </strong><a href="#" id="flip-btn" class="signup signup_link">Зарегестрируйся</a>
        </p>
    </div>
<?= $this->tag->endForm() ?>
