    <div class="page-header">
        <h2>Вход</h2>
    </div>
	<?= $this->tag->form(["login", 'class' => 'login-form']) ?>
    <div class="form-group">
        <div class="input-group">
            <input type="text" name="email" class="form-control" placeholder="Email">
            <span class="input-group-addon">
                                          <i class="glyphicon glyphicon-user"></i>
                                      </span>
        </div>
    </div>
    <div class="form-group">
        <div class="input-group">
            <input type="password" name="password" class="form-control" placeholder="Пароль">
            <span class="input-group-addon">
                                          <i class="glyphicon glyphicon-lock"></i>
                                    </span>
        </div>
    </div>
    <div class="form-group sign-btn">
		<?= $this->tag->submitButton(["Вход", "class" => "btn"]) ?>
        <p>
            <br>
           Нет аккаунта? <a href="#" id="flip-btn" class="signup signup_link">Зарегестрируйся</a>
        </p>
    </div>
<?= $this->tag->endForm() ?>
