<?= $this->tag->form(["session/login", 'class' => 'login-form']) ?>
    <div class="form-group">
        <div class="input-group">
            <input type="email" name="email" class="form-control" placeholder="Email" autocomplete="off">
            <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
        </div>
    </div>
    <div class="form-group">
        <div class="input-group">
            <input type="password" name="password" class="form-control" placeholder="Пароль" autocomplete="off">
            <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
        </div>
    </div>
    <div class="form-group sign-btn">
		<?= $this->tag->submitButton(["Вход", "class" => "btn"]) ?>
        <p>
            <br>
            <strong>Нету акаунта? </strong><a href="#" id="flip-btn" class="signup signup_link">Зарегестрируйся</a>
        </p>
    </div>
<?= $this->tag->endForm() ?>