<form class="login-form">
	<div class="form-group">
		<div class="input-group">
			<input type="text" class="form-control" placeholder="Имя">
			<span class="input-group-addon">
                                          <i class="glyphicon glyphicon-user"></i>
                                      </span>
		</div>
	</div>
	<div class="form-group">
		<div class="input-group">
			<input type="password" class="form-control" placeholder="Пароль">
			<span class="input-group-addon">
                                          <i class="glyphicon glyphicon-lock"></i>
                                    </span>
		</div>
	</div>
	<div class="form-group">
		<div class="input-group">
			<input type="password" class="form-control" placeholder="Потвердить пароль">
			<span class="input-group-addon">
                                          <i class="glyphicon glyphicon-repeat"></i>
                                    </span>
		</div>
	</div>
	<div class="form-group">
		<div class="input-group">
			<input type="email" class="form-control" placeholder="Email">
			<span class="input-group-addon">
                                          <i class="glyphicon glyphicon-envelope"></i>
                                      </span>
		</div>
	</div>
	<div class="form-group sign-btn">
		<input type="submit" class="btn" value="Зарегестрировать">
		<br><br>
		<p>Есть акаунт? <a href="#" id="unflip-btn" class="signup">Войти</a></p>
	</div>
<?= $this->tag->endForm() ?>
